---
  - name: There is new update available
    # We run this command locally
    # TODO the staging host to decide if we have to deal with the vm or production server
    shell: "bin/dotenv utilities/new_version_available {{ ansible_ssh_host }}"
    delegate_to: localhost
    register: new_version_available
    ignore_errors: false
    changed_when: false

  - name: zypper up 'obs-api'
    command: 
      cmd: zypper -n update --best-effort --details obs-api
    when: new_version_available.rc == 0
    notify: 
      - ensure systemd
      - check_http_server_running
