version: 2.1

orbs:
 python: circleci/python@1.2

workflows:
  linter: 
    jobs:
      - linter


jobs:
  linter:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  
          pip-dependency-file: test-requirements.txt 
      - run:
          name: Run linter
          command: ansible-lint
